### ISSUE TITLE
Support highly available MongoDB via replica set

### ISSUE THREAD

**Issue by GanKanTechnology** [sitewhere/sitewhere-k8s#6]
Hi guys~
    I found that only one single pod for  mongodb running after deploying  sitewhere with helm. Do you have any idea that  how to  use  mongodb replica set  for sitewhere ? If  we don't use a mongodb replica set ,the application  data may loss in some cases. So it's necessary that we should consider about mongodb replica set and backup those data. Do you have any plan to develop this ,or any  suggestions please?
 Thank you & wish you a happy new year~

**Comment by derekadams** [comment]
The current Helm chart uses a k8s StatefulSet for the MongoDB instance, but we still need to test with replica set configurations. It should be straightforward as discussed in this entry:

https://kubernetes.io/blog/2017/01/running-mongodb-on-kubernetes-with-statefulsets/

We already have support in place for backing the MongoDB instances using Rook.io, so the redundancy for the underlying storage is there. We've also discussed using Kanister (https://kanister.io/) in order to make other aspects of persistence more configurable.

**Comment by derekadams** [comment]
Actually, it looks like there is a stable Helm chart for replicated MongoDB, so we may add that as a configuration option:

https://github.com/helm/charts/tree/master/stable/mongodb-replicaset

**Comment by GanKanTechnology** [comment]
Thank you for your reply, I'll test what you've mentioned. And I'll pay continous attention to your sitewhere--which seems a really prospective work.

**Comment by derekadams** [comment]
We have added HA versions of Zookeeper, Kafka, Consul, and MongoDB into the SiteWhere chart as of 2.0.2. There are some issues with the way we wait on Kafka to become available which will need to be addressed, but in general the system has out-of-the-box support for MongoDB replica sets now.
